# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - nginx
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
volumes:
  data: