# docker-compose.yml
version: '3.8'
services:
  app:
    image: cr.yandex/crphi8j27tk29ukginqn/cosmobot
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    networks:
      - awesome
  nginx:
    image: cr.yandex/crphi8j27tk29ukginqn/nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    networks:
      - awesome
  db:
    image: cr.yandex/crphi8j27tk29ukginqn/postgres
    restart: always
    build:
      context: ./db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    volumes: 
      - db_data:/var/lib/postgresql/data
    networks:
      - awesome
networks:
  awesome:
    driver: bridge
volumes:
  db_data: