name: Push To Yandex Cloud CR
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      CR_REGISTRY: crphi8j27tk29ukginqn
      CR_REPOSITORY: yc-cr-github-action
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Авторизация'
        run: echo "${{ secrets.TOKEN }}" | docker login -u oauth --password-stdin cr.yandex
      - name: 'Билд докера'
        run: docker-compose build --no-cache && docker-compose up --no-start
      - name: 'Пуш докера'
        run: docker-compose push
      - name: 'Подключение к серверу и запуск докера'
        uses: appleboy/ssh-action@master
        with:
          host: '158.160.14.230'
          username: 'yandex'
          key: ${{ secrets.SSH_KEY }}
          port: '22'
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm docker-compose.yml
            echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml
            sudo docker-compose down
            sudo docker rmi -f $(docker images -aq)
            sudo docker-compose up -d
